### ISSUE TITLE
lvim_helper_callback changed?

### ISSUE THREAD

**Issue by thepenguinthatwants** [lvim-tech/lvim-helper#4]
module 'lvim-helper.bindings' not found when I open nvim after updating to latest version.

```
lvim_helper_bindings.bindings = {
    ["n"] = lvim_helper_bindings.lvim_helper_callback("next"),
    ["q"] = lvim_helper_bindings.lvim_helper_callback("close")
}
```

Problematic configs are here, but not sure how to fix.

**Comment by lvim-tech** [comment]
Commit `d2af740` has a new API with critical changes - dependencies, new installation. If you want to use the old version - commit `7fe74bd`. For a new version - read the instructions in README.md
